version: '3'

volumes:
  loki_data: {}

services:
  loki:
    image: grafana/loki:latest
    volumes:
      - loki_data:/tmp
      - ./loki:/etc/loki
    command:
      - '--config.file=/etc/loki/loki.yml'
    restart: unless-stopped
    labels:
      - promtail.logs=true
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=3100
