version: '3'

volumes:
  loki_data: {}

x-logging: &logging
  logging:
    driver: 'json-file'
    options: 
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  loki:
    <<: *logging
    image: grafana/loki:latest
    volumes:
      - loki_data:/tmp
      - ./loki:/etc/loki
    command:
      - '--config.file=/etc/loki/loki.yml'
    restart: unless-stopped
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=3100
