version: '3.9'

volumes:
  promtail_data: {}

services:
  promtail:
    image: grafana/promtail:latest
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./promtail:/etc/promtail
      - promtail_data:/tmp
    entrypoint: ./etc/promtail/entrypoint.sh
    command: ["/usr/bin/promtail"]
    environment:
      SERVER_LABEL_HOSTNAME: ${LOGS_LABEL:-notset}
    restart: "unless-stopped"
    labels:
      - promtail.logs=true
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9080
