version: '3.9'

volumes:
  promtail_data: {}

x-logging: &logging
  logging:
    driver: 'json-file'
    options: 
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  promtail:
    image: grafana/promtail:latest
    user: root
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - ./promtail:/etc/promtail
      - promtail_data:/tmp

      # If using wsl
      # - /mnt/docker/data/docker/containers:/var/lib/docker/containers:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    entrypoint: ./etc/promtail/entrypoint.sh
    command: ["/usr/bin/promtail"]
    environment:
      SERVER_LABEL_HOSTNAME: ${LOGS_LABEL:-notset}
    restart: "unless-stopped"
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9080
    <<: *logging
